# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_answer_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
