# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160324_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='upvote',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_choice',
            field=models.CharField(choices=[('up', 'upvote'), ('down', 'downvote')], max_length=12, null=True),
        ),
    ]
