# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160324_2106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user', 'vote_choice')]),
        ),
    ]
