# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160324_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(to='app.Answer'),
        ),
    ]
