# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_question_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_choice',
            field=models.CharField(choices=[('up', 'upvote'), ('down', 'downvote')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user', 'answer')]),
        ),
    ]
